export const FETCH_DATA =
  "https://www.swiggy.com/dapi/restaurants/list/v5?lat=21.1702401&lng=72.83106070000001&page_type=DESKTOP_WEB_LISTING";

export const LOGO_URL =
  "https://w7.pngwing.com/pngs/333/12/png-transparent-infinity-food-logo.png";

export const CDN_URL =
  "https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/";

export const SIGNUP_URL =
  "https://identitytoolkit.googleapis.com/v1/accounts:signUp?key=AIzaSyBlvwm2UFysqlxp549MzHN_mTVXIn57d7s";

export const LOGIN_URL =
  "https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=AIzaSyBlvwm2UFysqlxp549MzHN_mTVXIn57d7s";

export const AUTH_LOGO =
  "https://img.lovepik.com/free-png/20210924/lovepik-burger-png-image_401316034_wh1200.png";

export const EMPTY_CART =
  "https://media.istockphoto.com/id/1369712605/vector/cooking-food-in-frying-pan-vector-illustration-of-cut-vegetables-cooked-on-gas-stove-cartoon.jpg?s=612x612&w=0&k=20&c=3H9TU5PosN-vYYFQCahK-RdA695_41QiT90n1re_0j0=";

export const DATA = [
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "123764",
        name: "Radhe Dhokla",
        uuid: "1d6cae2b-22a0-4c85-9370-9ee82f91c74c",
        city: "21",
        area: "Katargam",
        totalRatingsString: "",
        cloudinaryImageId: "27947ad42435b18fc7d1f127e841748a",
        cuisines: ["Chinese", "North Indian", "Biryani"],
        tags: [],
        costForTwo: 15000,
        costForTwoString: "₹150 FOR TWO",
        deliveryTime: 46,
        minDeliveryTime: 46,
        maxDeliveryTime: 46,
        slaString: "46 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "radhe-dhokla-varachha-varachha",
          city: "Surat",
        },
        cityState: "21",
        address: "",
        locality: "Balvant Nagar Society",
        parentId: 4921,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 6200,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 6200,
          message: "",
          title: "Delivery Charge",
          amount: "6200",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7321479~p=1~eid=00000189-9640-94bc-091d-dc620057010e~srvts=1690442962108~90088",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "12.7 kms",
        hasSurge: false,
        sla: {
          restaurantId: "",
          deliveryTime: 46,
          minDeliveryTime: 46,
          maxDeliveryTime: 46,
          lastMileTravel: 0,
          lastMileDistance: 12.7,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.3",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "537087",
        name: "Jalaram Khichdi",
        uuid: "0f3d8d50-3b9d-47a3-8934-bded9810daf2",
        city: "21",
        area: "Sachin",
        totalRatingsString: "",
        cloudinaryImageId: "beef51ea3e08aed5ffec413ed3d051f5",
        cuisines: ["Gujarati", "North Indian", "Chinese", "Snacks"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 29,
        minDeliveryTime: 29,
        maxDeliveryTime: 29,
        slaString: "29 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "jalaram-khichdi-sachin-sachin",
          city: "Surat",
        },
        cityState: "21",
        address: "",
        locality: "Gidc Chowkdi",
        parentId: 6010,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 1900,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 1900,
          message: "",
          title: "Delivery Charge",
          amount: "1900",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "3 kms",
        hasSurge: false,
        sla: {
          restaurantId: "",
          deliveryTime: 29,
          minDeliveryTime: 29,
          maxDeliveryTime: 29,
          lastMileTravel: 0,
          lastMileDistance: 3,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.9",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "215228",
        name: "Mahesh Pav Bhaji",
        uuid: "9748f01b-8e61-4b33-b723-940b2df2220a",
        city: "21",
        area: "Katargam",
        totalRatingsString: "",
        cloudinaryImageId: "f015ac61594dc1b4107f9b8735a8d2e7",
        cuisines: [
          "North Indian",
          "Chinese",
          "Fast Food",
          "Pizzas",
          "South Indian",
        ],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 49,
        minDeliveryTime: 49,
        maxDeliveryTime: 49,
        slaString: "49 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "mahesh-pav-bhaji-katargam-katargam",
          city: "Surat",
        },
        cityState: "21",
        address: "",
        locality: "Katargam",
        parentId: 6553,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 6200,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 6200,
          message: "",
          title: "Delivery Charge",
          amount: "6200",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7268956~p=2~eid=00000189-9640-94bc-091d-dc630057027d~srvts=1690442962108~90088",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "14.7 kms",
        hasSurge: false,
        sla: {
          restaurantId: "",
          deliveryTime: 49,
          minDeliveryTime: 49,
          maxDeliveryTime: 49,
          lastMileTravel: 0,
          lastMileDistance: 14.7,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.0",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "143715",
        name: "Jalaram Locho & Khaman",
        uuid: "84fcef83-ac6c-46e2-a327-a73eec4febd6",
        city: "21",
        area: "Katargam",
        totalRatingsString: "",
        cloudinaryImageId: "ewbovsuylb8e3ow3gcf2",
        cuisines: ["Gujarati", "North Indian", "Indian", "Sweets"],
        tags: [],
        costForTwo: 15000,
        costForTwoString: "₹150 FOR TWO",
        deliveryTime: 40,
        minDeliveryTime: 40,
        maxDeliveryTime: 40,
        slaString: "40 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "jalaram-locho-and-khaman-katargam-katargam",
          city: "Surat",
        },
        cityState: "21",
        address: "",
        locality: "Gotalavadi",
        parentId: 230558,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 6200,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 6200,
          message: "",
          title: "Delivery Charge",
          amount: "6200",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "11.5 kms",
        hasSurge: false,
        sla: {
          restaurantId: "",
          deliveryTime: 40,
          minDeliveryTime: 40,
          maxDeliveryTime: 40,
          lastMileTravel: 0,
          lastMileDistance: 11.5,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.2",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "584677",
        name: "Egg.Com",
        uuid: "7368cd03-125f-4a0f-a3ab-101c3a720fe3",
        city: "21",
        area: "Adajan Patiya",
        totalRatingsString: "",
        cloudinaryImageId: "jbgobqpliwfc9ixkfmdk",
        cuisines: ["Ice Cream", "Biryani"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 50,
        minDeliveryTime: 50,
        maxDeliveryTime: 50,
        slaString: "50 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "egg.com-adajan-adajan",
          city: "Surat",
        },
        cityState: "21",
        address: "",
        locality: "Sardar Complex",
        parentId: 76692,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 6200,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 6200,
          message: "",
          title: "Delivery Charge",
          amount: "6200",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7393845~p=3~eid=00000189-9640-94bc-091d-dc640057030f~srvts=1690442962108~90088",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "11.1 kms",
        hasSurge: false,
        sla: {
          restaurantId: "",
          deliveryTime: 50,
          minDeliveryTime: 50,
          maxDeliveryTime: 50,
          lastMileTravel: 0,
          lastMileDistance: 11.1,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.1",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "152983",
        name: "Jani Locho",
        uuid: "c91bc0e2-081e-4b78-8900-8cf07f86eba9",
        city: "21",
        area: "Adajan Patiya",
        totalRatingsString: "",
        cloudinaryImageId: "nni5t4imm0m5odzlqav6",
        cuisines: ["Gujarati", "Snacks"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 48,
        minDeliveryTime: 48,
        maxDeliveryTime: 48,
        slaString: "48 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "jani-locho-adajan-adajan",
          city: "Surat",
        },
        cityState: "21",
        address: "",
        locality: "Navyug College Road",
        parentId: 22262,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 6200,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 6200,
          message: "",
          title: "Delivery Charge",
          amount: "6200",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "11.8 kms",
        hasSurge: false,
        sla: {
          restaurantId: "",
          deliveryTime: 48,
          minDeliveryTime: 48,
          maxDeliveryTime: 48,
          lastMileTravel: 0,
          lastMileDistance: 11.8,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.3",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "598314",
        name: "Live Egg",
        uuid: "a91549f6-79ff-4f23-889f-8ec9a8b83b2d",
        city: "21",
        area: "Pal Gam",
        totalRatingsString: "",
        cloudinaryImageId: "oceioyx0jczl2whbaxud",
        cuisines: ["Ice Cream", "Biryani"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 56,
        minDeliveryTime: 56,
        maxDeliveryTime: 56,
        slaString: "56 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "egg.com-adajan-adajan-2",
          city: "Surat",
        },
        cityState: "21",
        address: "",
        locality: "Sardar Complex",
        parentId: 373211,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 6200,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 6200,
          message: "",
          title: "Delivery Charge",
          amount: "6200",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7393847~p=4~eid=00000189-9640-94bc-091d-dc6500570420~srvts=1690442962108~90088",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "11.1 kms",
        hasSurge: false,
        sla: {
          restaurantId: "",
          deliveryTime: 56,
          minDeliveryTime: 56,
          maxDeliveryTime: 56,
          lastMileTravel: 0,
          lastMileDistance: 11.1,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.0",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "76475",
        name: "Jakaas Chinese Food",
        uuid: "964c17c4-c3fa-460a-89dd-56838d77fa6b",
        city: "21",
        area: "Adajan Gam",
        totalRatingsString: "",
        cloudinaryImageId: "ngajktrkoa9iins4iwxh",
        cuisines: ["Chinese"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 50,
        minDeliveryTime: 50,
        maxDeliveryTime: 50,
        slaString: "50 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "jakaas-chinese-fast-food-adajan-adajan",
          city: "Surat",
        },
        cityState: "21",
        address: "",
        locality: "Vir Arjun Marg",
        parentId: 109236,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 6200,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 6200,
          message: "",
          title: "Delivery Charge",
          amount: "6200",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "12.2 kms",
        hasSurge: false,
        sla: {
          restaurantId: "",
          deliveryTime: 50,
          minDeliveryTime: 50,
          maxDeliveryTime: 50,
          lastMileTravel: 0,
          lastMileDistance: 12.2,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.3",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "448817",
        name: "Ganda Kaka Na Fafda",
        uuid: "47188809-f4fc-4be8-9692-ce33ad33e553",
        city: "21",
        area: "Haripura",
        totalRatingsString: "",
        cloudinaryImageId: "r9kvwmb7e8hrxmvjczzh",
        cuisines: ["Desserts"],
        tags: [],
        costForTwo: 20000,
        costForTwoString: "₹200 FOR TWO",
        deliveryTime: 38,
        minDeliveryTime: 38,
        maxDeliveryTime: 38,
        slaString: "38 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "ganda-kaka-na-fafda-athwa-athwa",
          city: "Surat",
        },
        cityState: "21",
        address: "",
        locality: "Bandugara Na Nake",
        parentId: 270163,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 6200,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 6200,
          message: "",
          title: "Delivery Charge",
          amount: "6200",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID:
          "cid=7561318~p=5~eid=00000189-9640-94bc-091d-dc660057053e~srvts=1690442962108~90088",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "10.3 kms",
        hasSurge: false,
        sla: {
          restaurantId: "",
          deliveryTime: 38,
          minDeliveryTime: 38,
          maxDeliveryTime: 38,
          lastMileTravel: 0,
          lastMileDistance: 10.3,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: true,
        avgRating: "4.1",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "65430",
        name: "Urban Punjab",
        uuid: "e88d0839-1b40-4cce-807a-9714072e2a5d",
        city: "21",
        area: "Adajan Gam",
        totalRatingsString: "",
        cloudinaryImageId: "fuog43zissspekqlbhtt",
        cuisines: [
          "Punjabi",
          "Indian",
          "North Indian",
          "Thalis",
          "Biryani",
          "Tandoor",
          "Chinese",
          "Pizzas",
          "Pastas",
        ],
        tags: [],
        costForTwo: 25000,
        costForTwoString: "₹250 FOR TWO",
        deliveryTime: 49,
        minDeliveryTime: 49,
        maxDeliveryTime: 49,
        slaString: "49 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "urban-punjab-athwa-athwa",
          city: "Surat",
        },
        cityState: "21",
        address: "",
        locality: "Anand Mahal Road",
        parentId: 5265,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 6200,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 6200,
          message: "",
          title: "Delivery Charge",
          amount: "6200",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "11.5 kms",
        hasSurge: false,
        sla: {
          restaurantId: "",
          deliveryTime: 49,
          minDeliveryTime: 49,
          maxDeliveryTime: 49,
          lastMileTravel: 0,
          lastMileDistance: 11.5,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.1",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "521285",
        name: "Shreeji Kathiyawadi Restaurant",
        uuid: "d534403c-b59a-4b60-b77d-4c839ffb9f4f",
        city: "21",
        area: "Katargam",
        totalRatingsString: "",
        cloudinaryImageId: "p6mauriwrq90vtlgerua",
        cuisines: ["North Indian"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 41,
        minDeliveryTime: 41,
        maxDeliveryTime: 41,
        slaString: "41 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "shreeji-kathiyawadi-restaurant-adajan-adajan",
          city: "Surat",
        },
        cityState: "21",
        address: "",
        locality: "Keshav Park Society",
        parentId: 285584,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 6200,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 6200,
          message: "",
          title: "Delivery Charge",
          amount: "6200",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "11.2 kms",
        hasSurge: false,
        sla: {
          restaurantId: "",
          deliveryTime: 41,
          minDeliveryTime: 41,
          maxDeliveryTime: 41,
          lastMileTravel: 0,
          lastMileDistance: 11.2,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.2",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "77585",
        name: "Bismillah",
        uuid: "3f6a4070-3e3d-4b1a-9cfe-00c6e3c763fc",
        city: "21",
        area: "New Textile Market",
        totalRatingsString: "",
        cloudinaryImageId: "p45uhozbhxnu1zltsfae",
        cuisines: ["Desserts", "Ice Cream"],
        tags: [],
        costForTwo: 15000,
        costForTwoString: "₹150 FOR TWO",
        deliveryTime: 50,
        minDeliveryTime: 50,
        maxDeliveryTime: 50,
        slaString: "50 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "bismillah-umarwada-varachha",
          city: "Surat",
        },
        cityState: "21",
        address: "",
        locality: "Railway Colony",
        parentId: 7587,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 6200,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 6200,
          message: "",
          title: "Delivery Charge",
          amount: "6200",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "10.5 kms",
        hasSurge: false,
        sla: {
          restaurantId: "",
          deliveryTime: 50,
          minDeliveryTime: 50,
          maxDeliveryTime: 50,
          lastMileTravel: 0,
          lastMileDistance: 10.5,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.3",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "664046",
        name: "Center Point -Poddar Arcade",
        uuid: "ec2ca6a6-3be1-4f08-b730-6b59ad9dea9f",
        city: "21",
        area: "Varachha",
        totalRatingsString: "",
        cloudinaryImageId: "909bd66b02831ac12cba8ae732a42c7c",
        cuisines: ["Fast Food", "Pizzas", "Burgers"],
        tags: [],
        costForTwo: 30000,
        costForTwoString: "₹300 FOR TWO",
        deliveryTime: 43,
        minDeliveryTime: 43,
        maxDeliveryTime: 43,
        slaString: "43 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "center-point-fast-food-varachha-varachha",
          city: "Surat",
        },
        cityState: "21",
        address: "",
        locality: "Poddar Arcade",
        parentId: 56323,
        unserviceable: false,
        veg: false,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 6200,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 6200,
          message: "",
          title: "Delivery Charge",
          amount: "6200",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "10.9 kms",
        hasSurge: false,
        sla: {
          restaurantId: "",
          deliveryTime: 43,
          minDeliveryTime: 43,
          maxDeliveryTime: 43,
          lastMileTravel: 0,
          lastMileDistance: 10.9,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "4.2",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
  {
    cardType: "restaurant",
    layoutAlignmentType: "VERTICAL",
    data: {
      type: "restaurant",
      data: {
        type: "F",
        id: "70750",
        name: "Surti Khaman House Adajan",
        uuid: "27a51c42-e9ca-4f38-b87a-bc77dee5a374",
        city: "21",
        area: "Anand Mahal",
        totalRatingsString: "",
        cloudinaryImageId: "vhqptzx28p1jo8dgxp1j",
        cuisines: ["Desserts"],
        tags: [],
        costForTwo: 18000,
        costForTwoString: "₹180 FOR TWO",
        deliveryTime: 46,
        minDeliveryTime: 46,
        maxDeliveryTime: 46,
        slaString: "46 MINS",
        lastMileTravel: 0,
        slugs: {
          restaurant: "surati-khaman-house-adajan-adajan",
          city: "Surat",
        },
        cityState: "21",
        address: "",
        locality: "Anand Mahal Road",
        parentId: 197899,
        unserviceable: false,
        veg: true,
        select: false,
        favorite: false,
        tradeCampaignHeaders: [],
        aggregatedDiscountInfoV2: {
          header: "",
          shortDescriptionList: [],
          descriptionList: [],
          subHeader: "",
          headerType: 0,
          superFreedel: "",
        },
        chain: [],
        feeDetails: {
          fees: [
            {
              name: "BASE_DISTANCE",
              fee: 6200,
              message: "",
            },
            {
              name: "BASE_TIME",
              fee: 0,
              message: "",
            },
            {
              name: "ANCILLARY_SURGE_FEE",
              fee: 0,
              message: "",
            },
          ],
          totalFees: 6200,
          message: "",
          title: "Delivery Charge",
          amount: "6200",
          icon: "",
        },
        availability: {
          opened: true,
          nextOpenMessage: "",
          nextCloseMessage: "",
        },
        longDistanceEnabled: 0,
        rainMode: "NONE",
        thirdPartyAddress: false,
        thirdPartyVendor: "",
        adTrackingID: "",
        badges: {
          imageBased: [],
          textBased: [],
          textExtendedBadges: [],
        },
        lastMileTravelString: "11.4 kms",
        hasSurge: false,
        sla: {
          restaurantId: "",
          deliveryTime: 46,
          minDeliveryTime: 46,
          maxDeliveryTime: 46,
          lastMileTravel: 0,
          lastMileDistance: 11.4,
          serviceability: "SERVICEABLE",
          rainMode: "NONE",
          preferentialService: false,
          iconType: "EMPTY",
        },
        promoted: false,
        avgRating: "3.9",
        totalRatings: 0,
        new: false,
      },
      subtype: "basic",
    },
    parentWidget: false,
  },
];
